RendERA/Controllers/MasterCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RendERA.DB.ViewModels;
using RendERA.ServiceManager.IServices;

namespace RendERA.Controllers
{
    public class MasterCategoryController : Controller
    {
        private readonly IMasterCategorySrv _masterCategoryService;
        private RendERA.ServiceManager.IServices.IAccountSrv _accountService;
        private readonly IHttpContextAccessor _contextAccessor; //for session

        public MasterCategoryController(IMasterCategorySrv masterCategoryService, IAccountSrv accountService, IHttpContextAccessor contextAccessor)
        {
            _accountService = accountService;
            _masterCategoryService = masterCategoryService;
            _contextAccessor = contextAccessor;
        }

        public IActionResult Index()
        {
            var value = _contextAccessor.HttpContext.Session.GetString(
                 RendERA.Infrastructure.Enum.SessionKey.LoggedInUserId.ToString());
            if (value == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var masterCategorys = new List<MasterCategoryVM>();
            var User = _accountService.GetUser(new Guid(value));
            masterCategorys = _masterCategoryService.GetAll();
            ViewBag.usertype = User.UserType;
            if (TempData["Msg"] != null)
                ViewBag.Msg = TempData["Msg"] as string;
            return View(masterCategorys);
        }

        public IActionResult Create()
        {
            var model = new MasterCategoryVM();
            return PartialView("_Create", model);
        }

        public IActionResult Edit(int id)
        {
            var value = _contextAccessor.HttpContext.Session.GetString(
                    RendERA.Infrastructure.Enum.SessionKey.LoggedInUserId.ToString());
            if (value == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var model = _masterCategoryService.GetById(id);
            return PartialView("_Edit", model);}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MasterCategoryVM model)
        {
            try
            {
                var value = _contextAccessor.HttpContext.Session.GetString(
                      RendERA.Infrastructure.Enum.SessionKey.LoggedInUserId.ToString());
                if (value == null)
                {
                    return RedirectToAction("Login", "Account");
                }
                var User = _accountService.GetUser(new Guid(value));
                if (ModelState.IsValid)
                {
                    if (IsAlreadyContain(model))
                    {
                        TempData["Msg"] = model.Name + " name is already exist";
                        return RedirectToAction("Index");
                    }
                    _masterCategoryService.Insert(model);
                    TempData["Msg"] = "Added successfully";
                }
            }
            catch
            {
                TempData["Msg"] = "Failed to add";
            }
            return RedirectToAction("Index");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MasterCategoryVM model)
        {
            try
            {
                var value = _contextAccessor.HttpContext.Session.GetString(
                      RendERA.Infrastructure.Enum.SessionKey.LoggedInUserId.ToString());
                if (value == null)
                {
                    return RedirectToAction("Login", "Account");
                }
                var User = _accountService.GetUser(new Guid(value));
                if (ModelState.IsValid)
                {
                    var masterCategory = _masterCategoryService.GetById(model.Id);
                    if (IsAlreadyContain(model))
                    {
                        TempData["Msg"] = model.Name + " name is already exist";
                        return RedirectToAction("Index");
                    }
                    masterCategory.Name = model.Name;
                    _masterCategoryService.Update(masterCategory);
                    TempData["Msg"] = "Updated successfully";
                }
            }
            catch
            {
                TempData["Msg"] = "Failed to Update";
            }
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            try
            {
                var value = _contextAccessor.HttpContext.Session.GetString(
                        RendERA.Infrastructure.Enum.SessionKey.LoggedInUserId.ToString());
                if (value == null)
                {
                    return RedirectToAction("Login", "Account");
                }
                _masterCategoryService.Delete(id);
                TempData["Msg"] = "Deleted Successfully";
            }
            catch
            {
                TempData["Msg"] = "Failed to Delete";
            }
            return RedirectToAction("Index");
        }

      
        private bool IsAlreadyContain(MasterCategoryVM model)
        {
            var list = _masterCategoryService.GetAll();
            foreach (var obj in list)
            {
                if (model.Name == obj.Name)
                {
                    return true;

                }
            }
            return false;
        }
    }
}

RendERA/Controllers/TeamsController.cs
using System;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using RendERA.ServiceManager.IServices;
using RendERA.DB.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;

namespace RendERA.Controllers
{
    
    public class TeamsController : Controller
    {
        private readonly ITeamSrv _teamService;
        private RendERA.ServiceManager.IServices.IAccountSrv _accountService;
        private readonly IHttpContextAccessor _contextAccessor; //for session

        public TeamsController(ITeamSrv teamService, IAccountSrv accountService, IHttpContextAccessor contextAccessor)
        {
            _accountService = accountService;
            _teamService = teamService;
            _contextAccessor = contextAccessor;
        }

        public  IActionResult Index()
        {
             var value = _contextAccessor.HttpContext.Session.GetString(
                  RendERA.Infrastructure.Enum.SessionKey.LoggedInUserId.ToString());
            if (value == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var teams = new List<TeamVM>();
            var User = _accountService.GetUser(new Guid(value));
            teams = _teamService.GetTeamListByPartnerId(User.UserId);            
            ViewBag.usertype = User.UserType;
            if (TempData["Msg"] != null)
                ViewBag.Msg = TempData["Msg"] as string;
            return View(teams);
        }
       
        public IActionResult TeamFilter() { 
            ViewBag.PartnerList = _accountService.GetAllUserByUserType((int)RendERA.Infrastructure.Enum.UserType.Partner);
            return View();
        }

        public IActionResult PartnerTeamList(string userId) {
            var value = _contextAccessor.HttpContext.Session.GetString(
                RendERA.Infrastructure.Enum.SessionKey.LoggedInUserId.ToString());
            if (value == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var teams = new List<TeamVM>();
            if (userId == "0")
            {
                teams = _teamService.GetAll();
            }
            else {
                var User = _accountService.GetUser(new Guid(userId));
                teams = _teamService.GetTeamListByPartnerId(User.UserId);
            }
            return PartialView("_PartnerTeamList", teams);
        }

        public IActionResult CreateTeam()
        {
            var model = new TeamVM();
            return PartialView("_Create", model);
        }

        public IActionResult EditTeam(int id)
        {
            var value = _contextAccessor.HttpContext.Session.GetString(
                    RendERA.Infrastructure.Enum.SessionKey.LoggedInUserId.ToString());
            if (value == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var model = _teamService.GetById(id);
            return PartialView("_Edit", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateTeam(TeamVM model)
        {
            try
            {
                var value = _contextAccessor.HttpContext.Session.GetString(
                      RendERA.Infrastructure.Enum.SessionKey.LoggedInUserId.ToString());
                if (value == null)
                {
                    return RedirectToAction("Login", "Account");
                }
                var User = _accountService.GetUser(new Guid(value));
                if (ModelState.IsValid)
                {
                    if (IsAlreadyContain(model)){
                        TempData["Msg"] =  model.Name + " name is already exist";
                        return RedirectToAction("Index");
                    }
                    if (model.ProfileImage != null)
                    {
                        string uniqueFileName = UploadedFile(model);
                        model.ProfilePicture = uniqueFileName;
                    }

                    model.PartnerId = User.UserId;
                    _teamService.Insert(model);
                    TempData["Msg"] = "Added successfully";
                }
            }
            catch
            {

                TempData["Msg"] = "Failed to add";
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditTeam(TeamVM model)
        {
            try
            {
                var value = _contextAccessor.HttpContext.Session.GetString(
                      RendERA.Infrastructure.Enum.SessionKey.LoggedInUserId.ToString());
                if (value == null)
                {
                    return RedirectToAction("Login", "Account");
                }
                var User = _accountService.GetUser(new Guid(value));
                if (ModelState.IsValid)
                {
                    var team = _teamService.GetById(model.Id);
                    if (IsAlreadyContain(model)){
                        TempData["Msg"] =  model.Name + " name is already exist";
                        return RedirectToAction("Index");
                    }
                    if (model.ProfileImage != null)
                    {
                        string uniqueFileName = UploadedFile(model);
                        team.ProfilePicture = uniqueFileName;
                    }
                    team.Degination = model.Degination;
                    team.Name = model.Name;
                    _teamService.Update(team);
                    TempData["Msg"] = "Updated successfully";
                }
            }
            catch
            {
                TempData["Msg"] = "Failed to Update";
            }
            return RedirectToAction("Index");
        }

        public IActionResult DeleteTeam(int id)
        {
            try
            {
                var value = _contextAccessor.HttpContext.Session.GetString(
                        RendERA.Infrastructure.Enum.SessionKey.LoggedInUserId.ToString());
                if (value == null)
                {
                    return RedirectToAction("Login", "Account");
                }
                _teamService.Delete(id);
                TempData["Msg"] = "Deleted Successfully";
            }
            catch
            {
                TempData["Msg"] = "Failed to Delete";
            }
            return RedirectToAction("Index");
        }

        private string UploadedFile(TeamVM model)
        {
            string uniqueFileName = null;

            if (model.ProfileImage != null)
            {
                string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\ProfileImg");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ProfileImage.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.ProfileImage.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        private bool IsAlreadyContain(TeamVM model)
        {
            var value = _contextAccessor.HttpContext.Session.GetString(
                 RendERA.Infrastructure.Enum.SessionKey.LoggedInUserId.ToString());
            var User = _accountService.GetUser(new Guid(value));
            var list = _teamService.GetTeamListByPartnerId(User.UserId);
            foreach (var obj in list)
            {
                if (model.Name == obj.Name) {
                    return true;
                }
            }
            return false;
        }

    }
}

RendERA/Views/MasterCategory/Index.cshtml
@model IEnumerable<RendERA.DB.ViewModels.MasterCategoryVM>
@{
    ViewData["Title"] = "Index";

    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    .msgForm {
        text-align: unset !important;
    }

    .Addbutton:hover {
        background-color: #ffffff;
        color: #292929;
    }

    .Addbutton {
        width: 76PX;
        padding: 8px;
        display: inline-block;
        position: relative;
        border: 2px solid #ffffff;
        background-color: transparent;
        color: #ffffff;
        font-size: 1em;
        font-family: "Roboto", sans-serif;
        line-height: 12px;
        letter-spacing: 0px;
        cursor: pointer;
        margin: 0;
        margin-bottom: 3px;
        white-space: nowrap;
        -webkit-transition: all 0.3s ease-out;
    }
</style>
 <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<div class="content js-content">
    <div style="padding: 11px;width:100%;display:none" class="content_item" id="CreateModal">
    </div>

    <div style="padding: 11px;width:100%" class="content_item">
        <input type="button" onclick="Add()" class="Addbutton btn bt-danger right fa fa-plus" value=" Add">
        <table class="table">
            <thead>
                <tr>

                    <th style="color:forestgreen">Name</th>

                    <th style="color:forestgreen">Edit</th>
                    <th style="color:forestgreen">Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var team in Model)
                {
                    <tr>
                        <td style="color:forestgreen">

                            @team.Name
                        </td>

                        <td><a id="@team.Id" onclick="Edit(this.id)" style="color:forestgreen">Edit</a></td>
                        <td><a onclick="change(@team.Id)" data-toggle="modal" data-target="#toModal" style="color:forestgreen">Delete</a></td>

                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>
<div id="toModal" class="modal fade" role="dialog" style="height: 200px !important">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style=" background: #3f4041;color:forestgreen">
                Are you want delete ?
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body " style="background-color: #333; height: 250px !important">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <div class="uploadpng">
                            <form asp-controller="Teams" id="" asp-action="DeleteTeam" method="post" enctype="multipart/form-data">
                                <input type="hidden" id="teamId" name="id" />
                                <input type="submit" style="padding: 8px;" class="btn bt-danger right" value="Delete">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade " id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style=" background: #3f4041;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Select parameter</h4>
            </div>
            <div class="modal-body bodydata" style=" background: #3f4041;">
            </div>

        </div>
    </div>
</div>
<div class="js-fake-scroll"></div>
<script>
    function change(value) {
        document.getElementById("teamId").value = value;
    }
    //$(document).ready(function () {
    //    $.get('Teams/CreateTeam',
    //        function (data) {
    //            $('#CreateModal').html(data);
    //        });
    //});

    $(document).on('click', '.editTeam', function () {
        // your function here
    });
    function Edit(id) {
        $("#CreateModal").css("display", "block")
        $.get('MasterCategory/Edit?id=' + id,
            function (data) {
                $("#CreateModal").html(data);
            });
    }
    function Add() {
        $("#CreateModal").css("display", "block");
        $(".Addbutton").css("display", "none");
        $.get('MasterCategory/Create',
            function (data) {
                $('#CreateModal').html(data);
            });
    }

</script>
@if (ViewBag.Msg != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert("@ViewBag.Msg");
        };
    </script>
}

RendERA/Views/MasterCategory/_Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@model RendERA.DB.ViewModels.MasterCategoryVM

<h3 style="padding: 8px; color:forestgreen">Create Category / Plugin</h3>
<form enctype="multipart/form-data" asp-action="Create">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label asp-for="Name" class="col-md-2 control-label" style="color:forestgreen"></label>
                <input asp-for="Name" class="col-md-4 msgForm" required />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <input style="padding: 8px;" class="btn bt-danger right" type="submit" value="submit" />
        <a asp-action="Index"><button style="padding: 8px;" type="button"><i class=""></i> Back to List</button></a>
    </div>
</form>
<div class="js-fake-scroll"></div>

RendERA/Views/MasterCategory/_Edit.cshtml
@{
    ViewData["Title"] = "EditTeam";
    Layout = null;
}
@model RendERA.DB.ViewModels.MasterCategoryVM

<h2 style="padding: 8px; color:forestgreen">Edit Category / Plugin</h2>
<form enctype="multipart/form-data" asp-action="Edit">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <input asp-for="Id" hidden />
                <label asp-for="Name" style="color:forestgreen" class="col-md-2 control-label"></label>
                <input asp-for="Name" class="col-md-4 msgForm" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
    </div>
   
    
    <div class="form-group">
        <input style="padding: 8px;" class="btn bt-danger right" type="submit" value="submit" />
        <a asp-action="Index"><button style="padding: 8px; color:forestgreen" type="button"><i class=""></i> Back to List</button></a>
    </div>
</form>
<div class="js-fake-scroll"></div>