RendERA/Controllers/JobTrackingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RendERA.DB.ViewModels;
using RendERA.ServiceManager.IServices;

namespace RendERA.Controllers
{
    public class JobTrackingController : Controller
    {
        private ServiceManager.IServices.IDocumentSrv _documentService;
        private readonly IMessagesSrv _messagesService;
        private readonly IMessageReplySrv _messageReplysService;
        private readonly IConfigurationSettingsSrv _ConfigurationSettingsSrvice;
        private readonly IParameterSrv _ParameterService;
        private readonly IJobLogSrv _JobLogService;
        private RendERA.ServiceManager.IServices.IAccountSrv _accountService;
        private readonly IHttpContextAccessor _contextAccessor; //for session

        public JobTrackingController(IConfigurationSettingsSrv ConfigurationSettingsSrvice, ServiceManager.IServices.IDocumentSrv documentService, RendERA.ServiceManager.IServices.IAccountSrv accountService, IHttpContextAccessor contextAccessor, IMessagesSrv messagesService, IMessageReplySrv messageReplysService, IParameterSrv ParameterService, IJobLogSrv JobLogService)
        {
            _JobLogService = JobLogService;
            _ParameterService = ParameterService;
            _messagesService = messagesService;
            _messageReplysService = messageReplysService;
            _accountService = accountService;
            _contextAccessor = contextAccessor;
            _documentService = documentService;
            _ConfigurationSettingsSrvice = ConfigurationSettingsSrvice;
        }
        
        public IActionResult Index()
        {
            
            return View();
        }
        public IActionResult GetTrackingDetails(string trackingId, int docId)
        {
            var jobTrackingList = new List<JobLogVM>();
            jobTrackingList = _JobLogService.GetTrackingListByDocumentId(docId);
            return PartialView("_GetTrackingDetails", jobTrackingList);
        }

        public IActionResult GetTrackingNotification()
        {
            var value = _contextAccessor.HttpContext.Session.GetString(
                      RendERA.Infrastructure.Enum.SessionKey.LoggedInUserId.ToString());
            if (value == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var User = _accountService.GetUser(new Guid(value));
            var jobTrackingList = new List<JobLogVM>();
            jobTrackingList = _JobLogService.GetLast10TrackingLogByUserId(User.UserId);
            ChangeToReadNotification(User.UserId);
            return PartialView("_GetTrackingNotification", jobTrackingList);
        }


        private void ChangeToReadNotification(Guid userId) {
            var user = _accountService.GetUser(userId);
            //only for user type
            if (user.UserType == (int)RendERA.Infrastructure.Enum.UserType.User) {
                var jobTrackingList = _JobLogService.GetLast10TrackingLogByUserId(userId);
                foreach (var jobTrac in jobTrackingList)
                {
                    if (jobTrac.IsRead == false)
                    {
                        jobTrac.IsRead = true;
                        _JobLogService.Update(jobTrac);
                    }
                }
            }
        }
    }
}

RendERA/Controllers/ParametersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RendERA.Common;
using RendERA.DB.ViewModels;
using RendERA.Models;
using RendERA.ServiceManager.IServices;

namespace RendERA.Controllers
{
    public class ParametersController : Controller
    {
        private ServiceManager.IServices.IDocumentSrv _documentService;
        private readonly IParameterSrv _parameterService;
        private readonly IJobLogSrv _jobLogService;
        private readonly IMasterCategorySrv _masterCategoryService;
        private readonly IPaymentTransactionSrv _PaymentTransactionService;
        private RendERA.ServiceManager.IServices.IAccountSrv _accountService;
        private readonly IHttpContextAccessor _contextAccessor; //for session

        public ParametersController(ServiceManager.IServices.IDocumentSrv documentService, IPaymentTransactionSrv PaymentTransactionService, RendERA.ServiceManager.IServices.IAccountSrv accountService, IHttpContextAccessor contextAccessor, IParameterSrv ParameterService, IMasterCategorySrv masterCategoryService, IJobLogSrv jobLogService)
        {
            _parameterService = ParameterService;
            _masterCategoryService = masterCategoryService;
            _PaymentTransactionService = PaymentTransactionService;
            _accountService = accountService;
            _contextAccessor = contextAccessor;
            _documentService = documentService;
            _jobLogService = jobLogService;
        }
        public IActionResult Index()
        {
            var model = GetDocumentParameters();
            ViewBag.CategoryList = GetCategoryListItems();
            if (TempData["Msg"] != null)
                ViewBag.Msg = TempData["Msg"] as string;
            return View(model);
        }

        public IActionResult SetParameter(int id)
        {
            try
            {
                var model = _parameterService.GetSelectedParameterByDocId(id);
                model.DocumentId = id;
                var parmeter = _parameterService.GetById(model.SelectedCPU);
                var transaction = _PaymentTransactionService.GetByDocId(model.DocumentId);
                if (transaction != null) {
                    model.Transaction = transaction;
                } else {
                    model.Transaction = new PaymentTransactionVM();
                }
                if (parmeter != null)
                {
                    model.Is2XCPU = parmeter.Category == (int)RendERA.Infrastructure.Enum.Category.CPU2X ? true : false;
                }
                model.CPUList = _parameterService.GetCPUList();
                model.TwoXCPUList = _parameterService.Get2XCPUList();
                model.ProcessorModelList = _parameterService.GetProcessorModelList();
                model.ProcessorTypeList = _parameterService.GetProcessorTypeList();
                var nodesForProjectRederding = _parameterService.GetNodesForProjectRederding();
                var renderTimeOfFrame = _parameterService.GetRenderTimeOfFrame();
                if (nodesForProjectRederding != null)
                {
                    model.PriceOfRenderTimePerSec = nodesForProjectRederding.Price;
                }
                if (renderTimeOfFrame != null)
                {
                    model.PriceOfPerNodeForProjectRender = renderTimeOfFrame.Price;
                }
                var doc = _documentService.GetDocById(model.DocumentId);
                model.IsSubmitted = doc.IsSubmitted == null ? false : (bool)doc.IsSubmitted;
                model.IsParameter = doc.IsParameter;
                if (transaction != null)
                {
                    return PartialView("_SubmittedJobDoc", model);
                }
                else
                {
                    return PartialView("_SetParameter", model);
                }
            }
            catch
            {
                TempData["Msg"] = "Something went wrong";
                return RedirectToAction("UserDashboard", "Home");
            }
        }

        [HttpPost]
        public IActionResult SetParameter(DocParametersMapVM model)
        {
            try
            {
                if (model != null && model.DocumentId > 0)
                {
                    _parameterService.SetParameterByDocId(model);
                    //save Transaction details
                    if (model.Transaction.Status != null) {
                        _PaymentTransactionService.Insert(model.Transaction);
                        if (model.Transaction.Status == "COMPLETED") {
                            ProceedPayment(model.DocumentId);
                        }
                    }
 

                    // set paramter is true
                    var doc = _documentService.GetDocById(model.DocumentId);
                    doc.IsParameter = true;
                    TempData["Msg"] = "Parameter set successfully";
                    if (model.IsSubmitted == true) {
                       // doc.IsSubmitted = true;
                       // doc.TransactionId = model.TransactionId;

                        TempData["Msg"] = "Submitted successfully";
                    }
                    _documentService.UpdateDoc(doc);
                }
                return RedirectToAction("Analytics", "Home");
            }
            catch (Exception ex)
            {
                TempData["Msg"] = "Something went wrong";
                return RedirectToAction("UserDashboard", "Home");
            }
        }

        public IActionResult AdditionalParameter(int id)
        {
            try
            {
                var model = GetAdditionalParaByDocId(id);
                model.DocumentId = id;

                return View(model);
                // return PartialView("_SetAdditionalParameter", model);
            }
            catch (Exception ex)
            {
                TempData["Msg"] = "Something went wrong";
                return RedirectToAction("UserDashboard", "Home");
            }
        }

        public IActionResult SetAdditionalParameter(int id)
        {
            try
            {
                var model = GetAdditionalParaByDocId(id);
                model.DocumentId = id;
                var doc = _documentService.GetDocById(model.DocumentId);
                var transaction = _PaymentTransactionService.GetByDocId(model.DocumentId);
                model.IsSubmitted = doc.IsSubmitted == null ? false : (bool)doc.IsSubmitted;
                if (transaction!= null)
                {
                    return PartialView("_SubmittedAdditionalParameter", model);
                }
                else
                {
                    return PartialView("_SetAdditionalParameter", model);
                }
            }
            catch (Exception ex)
            {
                TempData["Msg"] = "Something went wrong";
                return RedirectToAction("UserDashboard", "Home");
            }
        }

        [HttpPost]
        public JsonResult AdditionalParameter(AdditionalParameterVM model)
        {
            try
            {
                var value = _contextAccessor.HttpContext.Session.GetString(
                   RendERA.Infrastructure.Enum.SessionKey.LoggedInUserId.ToString());
                
                var User = _accountService.GetUser(new Guid(value));
                if (model != null)
                {
                    var dropdownlist = model.DropDownFields;
                    if (dropdownlist != null) {
                        foreach (var dropdown in dropdownlist)
                        {
                            _parameterService.InsertDropdownDocParaMapping(model.DocumentId, dropdown);
                        }
                    }
                    var inputFields = model.InputFields;
                    if (inputFields != null)
                    {
                        foreach (var input in inputFields)
                        {
                            _parameterService.InsertInputDocParaMapping(model.DocumentId, input);
                        }

                    }

                       //Add job log
                        SetJobLog(new JobLogVM
                        {
                            DocumentId = model.DocumentId,
                            Status = (int)RendERA.Infrastructure.Enum.JobTrackingStatus.InProgress,
                            LogDetail = "Parameters changed  for the Job by "+ User.UserName
                        });

                    return Json(new { status = "Success", message = "Success" });
                }
                return Json(new { status = "failed", message = "failed" });
            }
            catch (Exception ex)
            {
                TempData["Msg"] = "Something went wrong";
                // return Json("ok");
                return Json(new { status = "failed", message = "failed" });
            }
        }

        public JsonResult ValidateCouponCode(string code)
        {
            try
            {
                var discountParameter = _parameterService.validateCouponCode(code);
                if (discountParameter == null) {
                    return Json(new { status = "failed", discount = 0, couponId = 0 });
                }
                return Json(new { status = "Success", discount = discountParameter.Price, couponId = discountParameter.Id });

            }
            catch (Exception ex)
            {
                TempData["Msg"] = "Something went wrong";
                // return Json("ok");
                return Json(new { status = "failed", discount = 0, couponId = 0 });
            }
        }

        [HttpPost]
        public IActionResult InsertParameter(ParametersVM model)
        {
            if (model != null)
            {

RendERA/Views/Home/Analytics.cshtml
@model IEnumerable<RendERA.DB.ViewModels.DocumentVM>
@{
    ViewData["Title"] = "Analytics";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<style>
    @@media(min-width: 992px) {
        .my-col-1 {
        width: 12.333333%;
        }       
    }
    .btn-default {
    color: #fffdfd;
    background-color: #222;
    border-color: #ccc;
    }
    .hover:hover {
        background-color: white;
        color:black;
    }
    .hover{
        color:white;
    }

</style>
    <script src="https://www.paypal.com/sdk/js?client-id=AanRzn_IIbiKBlSP1669Uy1QXy0UnBOQwiF-7R4vCjNEN4EdgOCIPhkJk7eAL0izfFRGCd_nEQ1cFzOy">

    </script>
<div id="analsys">
    <div class="anylsiscontain">
        <div class="row" >
            <div class="col-md-1 my-col-1 stret">
                <div class="check">
                    <input type="checkbox" name=""><span><h5 style="color: white; padding-top: 10px;padding-left: 20px;"> Tracking ID</h5></span>
                </div>
            </div>

            <div class="col-md-1 my-col-1">
                <div class="scene">
                    <h5 style="color: white; padding-top: 10px;padding-left: 20px;"> Scene Name</h5>
                </div>
            </div>

            <div class="col-md-1 my-col-1">
                <div class="status">
                    <h5 style="color: white; padding-top: 10px;padding-left: 20px;"> Status</h5>
                </div>
            </div>

            <div class="col-md-1 my-col-1">
                <div class="start">
                    <h5 style="color: white; padding-top: 10px;padding-left: 20px;"> Starting Time</h5>
                </div>
            </div>
            <div class="col-md-1 my-col-1">
                <div class="end">
                    <h5 style="color: white; padding-top: 10px;padding-left: 20px;"> End Time</h5>
                </div>
            </div>
            <div class="col-md-1 my-col-1">
                <div class="dur">
                    <h5 style="color: white; padding-top: 10px;padding-left: 20px;"> Duration</h5>
                </div>
            </div>
            <div class="col-md-1 my-col-1">
                <div >
                    @*<h5 style="color: white; padding-top: 10px;padding-left: 20px;"> Parameter</h5>*@
                </div>
            </div>
        </div>
    </div>

    @foreach (var item in Model)
    {
        <div class="anylsiscontain" style="padding-top:9px;">
            <div class="row"  onclick="TrackingDetail('@item.TrackingId',@item.Id);">
                <input hidden class="parameterId" value="@item.Id" />
                <div class="col-md-1 my-col-1 stret">
                    <div class="check">
                        <input type="checkbox" style="margin-top: 4px;margin-right: 8px;" name=""><span class="hover"  onclick="TrackingDetail('@item.TrackingId',@item.Id);"><a href="#" style="padding:2px 14px;"> @Html.DisplayFor(modelItem => item.TrackingId)</a></span>
                    </div>
                </div>

                <div class="col-md-1 my-col-1"   onclick="TrackingDetail('@item.TrackingId',@item.Id);">
                    <div class="scene">
                        <p style=" color: white ; padding-left: 20px ; ">@Html.DisplayFor(modelItem => item.FileName)</p>
                    </div>
                </div>

                <div class="col-md-1 my-col-1"   onclick="TrackingDetail('@item.TrackingId',@item.Id);">
                    <div class="status">
                        <p style=" color: white ; padding-left: 20px ; ">
                            @RendERA.Infrastructure.Enum.GetEnumDescription((RendERA.Infrastructure.Enum.JobTrackingStatus)item.status)
                        </p>
                    </div>
                </div>

                <div class="col-md-1 my-col-1"   onclick="TrackingDetail('@item.TrackingId',@item.Id);">
                    <div class="start">
                        <p style=" color: white ; padding-left: 20px ; "> @item.DatePosted.ToString("MM/dd/yyyy hh:mm tt")</p>
                    </div>
                </div>
                <div class="col-md-1 my-col-1"   onclick="TrackingDetail('@item.TrackingId',@item.Id);">
                    <div class="end">
                        <p style=" color: white ; padding-left: 20px ; ">  - </p>
                    </div>
                </div>
                <div class="col-md-1 my-col-1"   onclick="TrackingDetail('@item.TrackingId',@item.Id);">
                    <div class="dur">
                        <p style=" color: white ; padding-left: 20px ; "> - </p>
                    </div>
                </div>
                <div class="col-md-1 my-col-1">
                    <div class="">
                        <button class="btn btn-default"  id="@item.Id" style=" padding-left: 20px ; " onclick="Details12(this.id)">Parameters</button>
                    </div>
                </div>
            </div>
        </div>

    }
    @if (Model == null)
    {
        <div class="nojobimg">

        </div>
    }




</div>
<div class="modal fade " id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content bodydata">
            @*<div class="modal-header" style=" background: #3f4041;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Select parameter</h4>
            </div>
            <div class="modal-body " style="padding: 0 56px;background: #3f4041;">


            </div>*@

        </div>
    </div>
</div>
<div class="modal fade" id="myNotificationModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content" id="" style=" width: 53%; margin-left: 23%;">
            <div class="modal-header" style=" background: #3f4041;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body" id="Trackingbodydata" style="padding: 0 56px;background: #3f4041;">


            </div>
            <div class="modal-footer" style=" background: #3f4041;">
                <div class="row">
                    <div class="col-md-6">
                    </div>
                    <div class="col-md-6">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




@*<table style="background-color:orange; width:100%; border:solid 5px green; padding:20px;">

        <tr>
            <td align="center" style="padding:20px;">
                <a href="javascript:void(0);" class="getAllEMP" style="font-size:20pt;">Get All Employee Inforamtion</a>
            </td>
        </tr>
    </table>

    <div id='myModal' class='modal' style="text-align:right; ">
        <div class="modal-dialog" style="width:900px; height:400px; padding:10px;">
            <div class="modal-content" style="overflow: auto; padding:10px; background-color:#d2f5f4;">
                <button type="button" id="closbtn">x</button>
                <div style="height:10px;"></div>
                <div id='myModalContent' style="width:850px; height:400px; padding:10px;"></div>
            </div>
        </div>
    </div>*@
@*<script>
        var ajaxCallURL = '/Employee/Deytai';
        $(function () {
            $(".getAllEMP").click(function () {
                var $buttonClicked = $(this);
                var options = { "backdrop": "static", keyboard: true };
                $.ajax({
                    type: "GET",
                    url: ajaxCallURL,
                    contentType: "application/json; charset=utf-8",
                    datatype: "json",
                    success: function (data) {
                        $('#myModalContent').html(data);
                        $('#myModal').modal(options);
                        $('#myModal').modal('show');
                    },
                    error: function () {
                        alert("Content load failed.");
                    }
                });
            });
            $("#closbtn").click(function () {
                $('#myModal').modal('hide');
            });
        });
    </script>*@
<script>
    function TrackingDetail(trackingId,docId){
        $.get('@Url.Action("GetTrackingDetails","JobTracking")?trackingId=' + trackingId + '&docId=' + docId,
            function (data) {
                $('.bodydata').html(data);
            });
        jQuery.noConflict();
        $("#myModal").modal("show");
    }

    function Details12(id) {
        if (id == '0' || id == 0) {
            var value = $("#DocumentList").val();
            id = parseInt(value);
        }
        if (id == '0' || id == 0) {

        }
        else {
              //window.location.assign('../../Parameters/AdditionalParameter?id=' + id);
            $.get('@Url.Action("SetAdditionalParameter","Parameters")?id=' + id,
                function (data) {
                    $('.bodydata').html(data);
                });
            jQuery.noConflict();
            $("#myModal").modal("show");
        }
    }
</script>
@if (ViewBag.Msg != null)
{
    <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Msg");
            };
    </script>
}
<script>
    function showActive() {
        var element = document.getElementById("Analytics");
        element.classList.add("active");
    }
    showActive();
</script>

RendERA/Views/Home/Assets.cshtml
@{
    ViewData["Title"] = "Assets";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";

}
@{
    var guid = new Guid("00000000-0000-0000-0000-000000000000");
}
<style>
    .hover:hover {
    background-color:white;
    color:black;
    }
</style>
<script src="https://cdnjs.cloudflare.com/ajax/7   s/jquery/3.3.1/jquery.min.js"></script>
<div id="assets">
    <div class="upload">
        <div class="row">
            <div class="col-md-4 input">
                <h5 style="color: grey; padding-top: 10px;">Uploading Notes <i class="fa fa-exclamation-circle" aria-hidden="true"></i></h5>
            </div>
            <div class="col-md-3">
            </div>
            <div class="col-md-5 uptput">
                <button class="btn btn-success input">Input</button>
                <button class="btn btn-success output">Output</button>
            </div>
        </div>
    </div>
    <form id="target" asp-controller="Documents" asp-action="UploadFile" method="post" enctype="multipart/form-data">
        <input style="width: 230px; display :none" id="file-input" required type="file" name="file" class="form-control">
    </form>
    <div class="cont icohei">
        <div class="row" style="height: 50px;">
            <div class="col-md-8">
                <div class="icondiv">
                    <ul>
                        <li><i type="button" id="button" class="fa fa-upload" aria-hidden="true"></i> </li>
                        <li> <i class="fa fa-folder-open" aria-hidden="true"></i> </li>
                        <li> <i class="fa fa-file" aria-hidden="true"></i> </li>
                        <li> <i class="fa fa-download" aria-hidden="true"></i> </li>
                        <li> <i class="fa fa-arrows" aria-hidden="true"></i> </li>
                        <li> <i class="fa fa-copy" aria-hidden="true"></i> </li>
                        <li> <i class="fa fa-pencil-square" aria-hidden="true"></i> </li>
                        <li> <i class="far fa fa-file-archive-o" aria-hidden="true"></i> </li>
                        <li> <i class="fa fa-trash" aria-hidden="true"></i> </li>
                        <button class="btn btn-success">Keep local path</button>
                    </ul>
                    <div class="icondiv" style="color: white;"> </div>
                </div>
                <div class="forhide">
                    <ul>
                        <li> <i class="fa fa-download" aria-hidden="true"></i> </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3">
                <div class="searchdiv ">
                    <div class="pull-right myi">
                        <input type="text" name="search" id="SearchByTrackId" placeholder="Search by Tracking Id"> <button><i class="fa fa-search" aria-hidden="true"></i></button><br> <p style="color: #fffdfd5c;padding-left: 92px;">Already Loaded ,total 0</p>
                        @*<input type="text" name="search" placeholder="Search in Current Directory"> <button><i class="fa fa-search" aria-hidden="true"></i></button><br> <p style="color: #fffdfd5c;padding-left: 92px;">Already Loaded ,total 0</p>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="rootdir">
        <p>Root directory</p>
    </div>
    <div class="" style="overflow: hidden;color: white;">
        <div style="padding: 11px;" class="content_item" id="userDocumentList">
            
        </div>
    </div>
    <div class="pdiv">

    </div>
</div>
<div class="modal fade " id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content bodydata">
            @*<div class="modal-header" style=" background: #3f4041;">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Select parameter</h4>
                </div>
                <div class="modal-body " style="padding: 0 56px;background: #3f4041;">


                </div>*@

        </div>
    </div>
</div>
<div class="modal fade" id="myNotificationModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content" id="" style=" width: 53%; margin-left: 23%;">
            <div class="modal-header" style=" background: #3f4041;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body" id="Trackingbodydata" style="padding: 0 56px;background: #3f4041;">


            </div>
            <div class="modal-footer" style=" background: #3f4041;">
                <div class="row">
                    <div class="col-md-6">
                    </div>
                    <div class="col-md-6">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@if (ViewBag.Msg != null)
{
    <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Msg");
            };
    </script>
}
<script>
    //let span = document.getElementsByClassName("assests");
    //let classes = span.classList;
    //classes.add("active");
    //span.textContent = classes;
    //function Edit(id) {
    // //   $("#CreateModal").css("display", "block")
    //    $.get('/Home/GetListofUserDocument?filter=' + filter,
    //        function (data) {
    //            $("#userDocumentList").html(data);
    //        });
    //}

     document.onreadystatechange = function () {
        if (document.readyState === "complete") {

            $("#SearchByTrackId").keyup(function (e) {

                $.get('@Url.Action("GetListofUserDocument","Home")?filter=' + $("#SearchByTrackId").val(),
            function (data) {
                $("#userDocumentList").html(data);
            });
    });

    function Doclist() {
                $.get('@Url.Action("GetListofUserDocument","Home")?filter=0',
            function (data) {
                $("#userDocumentList").html(data);
            });
    }
    Doclist();
        }
        else {
            window.onload = function () {

                $("#SearchByTrackId").keyup(function (e) {

                    $.get('@Url.Action("GetListofUserDocument","Home")?filter=' + $(this).val(),
            function (data) {
                $("#userDocumentList").html(data);
            });
    });

    function Doclist() {
                    $.get('@Url.Action("GetListofUserDocument","Home")?filter=0',
            function (data) {
                $("#userDocumentList").html(data);
            });
    }
    Doclist();
                $("#activeSoftwareList li:first").addClass("activeSoftware");
            };
        };
    }

    //$("#SearchByTrackId").keyup(function () {

    //    $.get('/Home/GetListofUserDocument?filter=' + filter,
    //        function (data) {
    //            $("#userDocumentList").html(data);
    //        });

    //});

    function showActive() {
        var element = document.getElementById("assests");
        element.classList.add("active");
    }
    showActive();
    //var element = document.getElementsByClassName("assests");
    //element.classList.add("active");

    function TrackingDetail(trackingId, docId) {
        $.get('@Url.Action("GetTrackingDetails","JobTracking")?trackingId=' + trackingId + '&docId=' + docId,
            function (data) {
                $('.bodydata').html(data);
            });
        jQuery.noConflict();
        $("#myModal").modal("show");
    }
</script>